version: '2'
services:
    starpointsapp-app:
        image: starpointsapp
        external_links:
            - starpointsapp-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/starpointsapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    starpointsapp-mysql:
        extends:
            file: mysql.yml
            service: starpointsapp-mysql
